server:
  port: 8080

graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: true
    cors:
      allowed-methods: GET, HEAD, POST
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true
  tools:
    schema-location-pattern: graphql/schemaNewCar.graphql
    introspection-enabled: true
  extended-scalars: BigDecimal, Date

graphiql:
  mapping: /graphiql
  endpoint:
    graphql: /graphql
  static:
    basePath: /
  enable: true
  pageTitle: GraphiQL
  propos:
    resources:
      defaultQuery: graphql/schemaNewCar.graphql
    variable:
      editorTheme: solarized light

spring:
  datasource:
    url: jdbc:mysql://localhost/graphQL?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  level:
    com.deeeplabs.sgemote: DEBUG
    org.hibernate: ERROR
    org.springframework: INFO